### ISSUE TITLE
No CUI output for "problem" NamedEntity

### ISSUE THREAD

**Issue by MadhumitaSushil** [UTHealth-CCB/clamp-support#20]
On running the pre-distributed attribute pipeline in version 1.4.0, I do not get any CUIs for "problem" semantic type. However, CUIs are present for other semantic types.

**Comment by jingqihit** [comment]
Hi,

Could you please try this version:

https://drive.google.com/open?id=1dun5regm_IOsWp3kY98J0pHvDOI7QqAc

You can use the same SN number to activate it and then run the attribute pipeline.
Let me know if you can see CUIs with this version.

Thanks,
Jingqi

**Comment by MadhumitaSushil** [comment]
Hi,

Thanks for the link! I get the following error message on activation:
activation failed. status=[461], desc=[The Serial Num. is invalid: IT IS NOT A LICENSED SN.]

Regards,
Madhumita

**Comment by jingqihit** [comment]
Try this one:
TAW3CL96

**Comment by MadhumitaSushil** [comment]
Thanks, this works, and additionally also gives me SNOMED_CT IDs :)
