### ISSUE TITLE
Clamp not Launching

### ISSUE THREAD

**Issue by xiaoteng-m** [UTHealth-CCB/clamp-support#29]
Hi, 

My problem is as follows:
_StartClamp.exe_ stopped working since some point. Re-installing CLAMP doesn't work. With Task Manager, I observed the _StartClamp.exe_ quits shortly after it is launched, without getting the main program started. I found the following message in the in _workspace/.metadata/.log_:

>  !SESSION 2019-07-01 17:11:09.216 -----------------------------------------------
> eclipse.buildId=unknown
> java.version=1.8.0_121
> java.vendor=Oracle Corporation
> BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
> Command-line arguments:  -os win32 -ws win32 -arch x86_64
> 
> !ENTRY org.eclipse.core.resources 2 10035 2019-07-01 17:11:09.997
> !MESSAGE The workspace exited with unsaved changes in the previous session; refreshing workspace to recover changes.

I think the issue might be caused by the unsaved changes in workspace. But this issue is resistant to re-installing. Would there be anyway I can manually solve the issue? 

Thank you in advance.

**Comment by jingqihit** [comment]
Hi,
Could you please download from here and activate with the new SN:
https://drive.google.com/open?id=13u7EhPy1T8Z-_H26MC5t8LHKLBiZojBy
J5S8GV4F
Let me know if it works.

Thanks,
Jingqi

**Comment by xiaoteng-m** [comment]
Hi,

Thank you for the new version. It works!

Sincerely,
Xiaoteng
