### ISSUE TITLE
Use annotations from other tools in Clamp

### ISSUE THREAD

**Issue by Medical-NLP** [UTHealth-CCB/clamp-support#35]
How to use annotations from other tools in Clamp? The format is different from the xmi files generated in Clamp.

**Comment by yaoyun-dev** [comment]
Hi Kevinw2013,

Thanks for your question.
You can convert the format to xmi conveniently using Clamp APIs
Clamp provides APIs to create and save xmi, together with collections of text, name entities and relations inside.

**Comment by Medical-NLP** [comment]
Thanks.

Could you please provide some example code about using Clamp APIs to convert the annotation format of other tools to the xmi format used in Clamp?

**Comment by yaoyun-dev** [comment]
Sure. Will share the sample code in github.

**Comment by Medical-NLP** [comment]
Great. Thanks.
