### ISSUE TITLE
In CLAMP CRE-based Name Entity Recognition component, there is a default model, where is it come from?

### ISSUE THREAD

**Issue by Mooooonica1** [UTHealth-CCB/clamp-support#38]

**Comment by melax-support** [comment]
Hi Mooooonica1,

Thanks for your question.
Yes, the default model is trained on 2000 UT Physician notes. We have experts who have a solid medical background to help annotate these notes manually.  Then train a CRF model using these corpus.

**Comment by Mooooonica1** [comment]
Got it. Thanks so much for your reply.
