### ISSUE TITLE
What is the difference between the Clamp cancer version and GUI version

### ISSUE THREAD

**Issue by codebee2020** [UTHealth-CCB/clamp-support#44]
I am doing research on cancer pathology notes and need to do clinical information extraction using natural language processing methods from free text of oncology first. I searched and found that Clamp has a version specifically developed for cancer. Could you please provide more detailed information about the Clamp cancer pipeline and the major differences from the original clamp GUI version?

Thanks a lot.

**Comment by yaoyun-dev** [comment]
Thanks for your interest in clamp. The oncology pipeline in clamp is designed to meet information needs from a broad community of users. The clinical concepts and relations extracted by this pipeline are designed mainly on pathology nodes. The general clinical nlp pipeline in clamp mainly extracts problem, treatment and test, together with their attributes.
