### ISSUE TITLE
CLAMP License Question

### ISSUE THREAD

**Issue by rwwarren** [UTHealth-CCB/clamp-support#47]
I am doing research for my university using CLAMP and we have a team of people using it on a few different computers. Is there any way we can get a license that isn't computer hardware ID + user based?

**Comment by jingqihit** [comment]
Unfortunately, we don't provide a group license to academic users now. They can apply for their own license if they're all for research purposes.

**Comment by rwwarren** [comment]
Sounds good! Thanks!
