### ISSUE TITLE
NegEx doesn't seem to work for me

### ISSUE THREAD

**Issue by aflwong** [UTHealth-CCB/clamp-support#66]
I wrote a simple code to test negation but it doesn't seem to work for me. Adapted from the smoking status example. Using CLAMP 1.6.3.

Here's a simple text to test. I can see 'PEANUT' semanticTag and assertion is 'absent' in 
`I do not have any peanut.`

`BLOCK(ForEach) Sentence{} {        
    ClampNameEntityUIMA{ FEATURE( "semanticTag", "PEANUT"), FEATURE( "assertion", "absent" ) 
        -> SETFEATURE( "semanticTag", "NoPeanut" ) };        
}`

![image](https://user-images.githubusercontent.com/73673971/98269294-29dc9280-1f53-11eb-94dc-7aed8ed4bfb3.png)

What am I missing?

**Comment by jingqihit** [comment]
Could you please share me a screen shot of your pipeline? The Ruta
component should be located after assertion component.

**Comment by aflwong** [comment]
Previous pipeline:
![image](https://user-images.githubusercontent.com/73673971/98277058-81cbc700-1f5c-11eb-845b-179599ca46f0.png)

That's it! I switched it around and it's now working. Thanks!
