### ISSUE TITLE
Annotation options

### ISSUE THREAD

**Issue by yvonne10** [UTHealth-CCB/clamp-support#69]
Hi I am starting corpus annotation on a small dataset. 
When I tried to specify 'Entities' in the typedefinition file, a right click on 'Entities'  gives me only the 'Add a new entity type' option.  
Based on the tutorial for Corpus Annotation, I should have a whole list of options e.g., 'Add child', 'Add attribute' 
How do I enable these options?

**Comment by jingqihit** [comment]
Hi, for the typedef.xml, you can create an entity type first, then right-click on the new entity type to 'add child'.
![image](https://user-images.githubusercontent.com/4357439/107396081-0cbfde80-6ac3-11eb-965a-bd65e3db87bf.png)
CLAMP cannot annotate attributes. It can define relations and assign 'from', and 'to' as attributes to that relation.
![image](https://user-images.githubusercontent.com/4357439/107396368-514b7a00-6ac3-11eb-9826-2ffcb0b9acbe.png)
![image](https://user-images.githubusercontent.com/4357439/107396476-66c0a400-6ac3-11eb-971c-1d2b526cd4d9.png)

Thanks,
Jingqi

**Comment by yvonne10** [comment]
Thank you, Jingqi for the clear explanation.
